/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";

const OverviewLazyRouteImport = createFileRoute("/overview")();

const OverviewLazyRoute = OverviewLazyRouteImport.update({
  id: "/overview",
  path: "/overview",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/overview.lazy").then((d) => d.Route));
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/overview": typeof OverviewLazyRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/overview": typeof OverviewLazyRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/overview": typeof OverviewLazyRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/overview";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/overview";
  id: "__root__" | "/" | "/overview";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  OverviewLazyRoute: typeof OverviewLazyRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/overview": {
      id: "/overview";
      path: "/overview";
      fullPath: "/overview";
      preLoaderRoute: typeof OverviewLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OverviewLazyRoute: OverviewLazyRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
